imports:
    - { resource: alias.yml }

services:
    _defaults:
        autowire: true
        bind:
            $root_path: '%core.root_path%'
            $php_ext: '%core.php_ext%'
            $table_prefix: '%core.table_prefix%'
            $ext_images_path: '%core.root_path%ext/david63/autodbbackup/adm/style/images'
        public: true

    david63.autodbbackup.admin.controller:
        class: david63\autodbbackup\controller\admin_controller

    david63.autodbbackup.core.functions:
        class: david63\autodbbackup\core\functions

    david63.autodbbackup.cron.task.auto_db_backup:
        class: david63\autodbbackup\cron\task\auto_db_backup
        calls:
            - [set_name, [cron.task.auto_db_backup]]
        tags:
            - { name: cron.task }
